site_name: Paige Haines ✹ Portfolio
site_url: https://paigehai.github.io.com/


theme:
  name: simple-blog
  custom_dir: overrides/
  favicon: assets/favicon.png
  palette:
    primary: deep purple
    accent: deep purple

extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/pygments/2.15.1/styles/material.min.css


markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      linenums: false

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/contrib/auto-render.min.js
  - js/katex.js

nav:
  - Hi, I'm Paige! 👋: index.md
  - Projects:
      - All Projects: projectsoverview/index.md
      - Design & Social Portfolio:
          - Overview: design.md
          - Copywriting Portfolio: projectsoverview/design/copywriting.md
          - GirlByte Website Design: projectsoverview/design/girlbyte.md
          - YouTube Thumbnail Designs: projectsoverview/design/thumbnails.md
          - Portfolio Version 1.0: projectsoverview/design/portfolio.md
      - GitHub Projects: github.md
  - Teaching: teaching.md
  - Academia: academia.md
  - Blog:
      - All Posts: blog/index.md
